# DevBox Privileged Windows Hosts Synchronizer
# AGENTS.md §15 (Local Domains) & §33 (Windows Administrator Model)

[CmdletBinding()]
param(
    [string[]]$Domains = @("erp.test", "myshop.test", "client.test")
)

$hostsPath = "$env:SystemRoot\System32\drivers\etc\hosts"
$markerBegin = "# BEGIN DEVBOX MANAGED HOSTS"
$markerEnd = "# END DEVBOX MANAGED HOSTS"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   DevBox Windows Hosts Manager - Privileged Sync" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# Check elevation
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[!] Administrative privileges required to modify $hostsPath." -ForegroundColor Yellow
    Write-Host "[*] Requesting UAC elevation..." -ForegroundColor Cyan
    try {
        Start-Process powershell.exe -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
    } catch {
        Write-Host "[-] Could not request UAC automatically in this session: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "[*] To sync manually, open PowerShell as Administrator and run:" -ForegroundColor Yellow
        Write-Host "    powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -ForegroundColor White
    }
    exit
}

if (-not (Test-Path $hostsPath)) {
    Write-Host "[-] Hosts file not found at: $hostsPath" -ForegroundColor Red
    exit 1
}

# Read SQLite database if available to get dynamically created domains
$dbPath = "D:\DevBox\data\devbox.sqlite"
if (Test-Path $dbPath) {
    try {
        # Check if node is available to query sqlite domains
        $json = & node -e "const { DatabaseSync } = require('node:sqlite'); try { const db = new DatabaseSync('$($dbPath.Replace('\', '/'))'); const rows = db.prepare('SELECT hostname FROM domains').all(); console.log(JSON.stringify(rows.map(r => r.hostname))); } catch(e) { console.log('[]'); }" 2>$null
        if ($json) {
            $parsed = ConvertFrom-Json $json
            if ($parsed.Count -gt 0) {
                $Domains = ($Domains + $parsed) | Select-Object -Unique
            }
        }
    } catch {}
}

Write-Host "[*] Synchronizing $($Domains.Count) DevBox domains to Windows Hosts:" -ForegroundColor Green
foreach ($d in $Domains) {
    Write-Host "    + 127.0.0.1 -> $d" -ForegroundColor White
}

# Build replacement block
$lines = @(
    $markerBegin,
    "# Automatically generated by DevBox Local Environment. Do not edit this section manually."
)
foreach ($d in $Domains) {
    $lines += "127.0.0.1 $d"
    $lines += "::1 $d"
}
$lines += $markerEnd
$block = $lines -join [System.Environment]::NewLine

try {
    $currentContent = [System.IO.File]::ReadAllText($hostsPath)
    $pattern = "(?s)# BEGIN DEVBOX MANAGED HOSTS.*?# END DEVBOX MANAGED HOSTS"

    if ($currentContent -match $pattern) {
        $newContent = [regex]::Replace($currentContent, $pattern, $block)
    } else {
        $newContent = $currentContent.TrimEnd() + [System.Environment]::NewLine + [System.Environment]::NewLine + $block + [System.Environment]::NewLine
    }

    [System.IO.File]::WriteAllText($hostsPath, $newContent, [System.Text.Encoding]::UTF8)
    Write-Host "[✓] Windows hosts file successfully updated!" -ForegroundColor Green

    # Flush DNS cache
    Write-Host "[*] Flushing Windows DNS resolver cache..." -ForegroundColor Gray
    ipconfig /flushdns | Out-Null
    Write-Host "[✓] Windows DNS Cache Flushed. Domains are active." -ForegroundColor Green
} catch {
    Write-Host "[-] Failed to write to hosts file: $_" -ForegroundColor Red
    exit 1
}

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "All DevBox domains (erp.test, myshop.test, client.test) are now live!" -ForegroundColor Green
Write-Host "Press any key to close this window..." -ForegroundColor Gray
Start-Sleep -Seconds 2
